version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67
        environment:
          TERM: xterm

    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages

      - run:
          name: Checking versions
          command: |
            node --version
            yarn --version

      - run:
          name: Installing dependencies
          command: yarn install --frozen-lock
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Building package
          command: yarn run build

      - run:
          name: Checking bundle size
          command: yarn run bundlesize

      - run:
          name: Unit tests
          command: yarn run test:unit --coverage --coverageReporters=text-lcov | node_modules/.bin/coveralls

      - run:
          name: Integration tests
          command: yarn run test:e2e
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
