version: 2
jobs:
  build:
    docker:
      # Docker image with Cypress dependencies
      - image: cypress/browsers:chrome67
        environment:
          # Enable colors in terminal output
          TERM: xterm

    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps

      - run:
          name: 'Checking node version'
          command: |
            node --version
            npm --version

      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: Building Atomic layout
          command: npm run build

      - run:
          name: Unit tests
          command: npm run test:unit -- --coverage --coverageReporters=text-lcov | node_modules/.bin/coveralls

      - run:
          name: Integration tests
          command: npm run test:e2e
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

      - run:
          name: Bundle size check
          command: node_modules/.bin/bundlesize
